blank_issues_enabled: false

contact_links:
  - name: 🇨🇿 Česká dokumentace
    url: https://github.com/pavorlechre/homeassistant-acond/blob/main/README.cs.md
    about: Dokumentace integrace v češtině.
  - name: 💬 Home Assistant Community Forum
    url: https://community.home-assistant.io/
    about: Pro obecné dotazy ohledně Home Assistant, ne přímo k integraci.
